[package]
name = "parser"
version.workspace = true
edition.workspace = true
description.workspace = true

[dependencies]
lexer = { path = "../lexer" }
utils = { path = "../utils" }
thiserror = { workspace = true }
