[package]
name = "utils"
version.workspace = true
edition.workspace = true
description.workspace = true

[dependencies]
unicode-properties = { version = "0.1.3", default-features = false, features = [
  "general-category",
] }
